---

- name: Create admin user
  uri:
    url: "http://{{ ansible_host }}:{{ archiva.port }}/{{ archiva.createAdminUserEndpoint }}"
    method: POST
    return_content: yes
    headers:
      Content-Type: "application/json"
    body_format: json
    body: "{{ archiva_admin | combine({ 'confirmPassword': archiva_admin.password }) | to_json }}"
